[build]
  builder = "nixpacks"
  buildCommand = "npx prisma generate --schema=apps/api/prisma/schema.prisma && npx prisma migrate deploy --schema=apps/api/prisma/schema.prisma && npm run build:api"

[deploy]
  startCommand = "node apps/api/dist/index.js"
  restartPolicyType = "on_failure"
  restartPolicyMaxRetries = 3
